export type CardManagement = {
  id: string;
  name: string;
  iccId: string;
  deviceId: string;
  deviceName: string;
  platformConfigId: string;
  operatorName: string;
  cardType: any;
  totalFlow: number;
  usedFlow: number;
  residualFlow: number;
  activationDate: string;
  updateTime: string;
  cardStateType: any;
  cardState: any;
  describe: string;
  platformConfigName: string;
  operatorPlatformType: any;
};
